SELECT
	"edad_18-25",
	"edad_26-35",
	"edad_36-49",
	"edad_50-65",
	"edad_65+",
	genero_masculino,
	genero_femenino,
	genero_no_binario,
	genero_trans,
	seg_personal,
	seg_preferencial,
	seg_plus,
	vivienda_arrendada,
	vivienda_familiar,
	vivienda_no_informa,
	vivienda_propia,
	ingresos_mensuales,
	total_egresos_mensuales,
	total_activos,
	total_pasivos,
	total_patrimonio,
	tiene_cuenta,
	saldo_cuenta,
	tiene_bolsillo,
	saldo_bolsillo,
	tiene_fiducuenta,
	saldo_fiducuenta,
	tiene_inversion,
	saldo_inv_virtual,
	tiene_invesbot,
	saldo_invesbot,
	liquidez,
	CASE WHEN capacidad_de_ahorro < 0 THEN 0.0 ELSE capacidad_de_ahorro END AS capacidad_de_ahorro,
	capacidad_endeudamiento,
	invierte,
	cantidad_productos_inversion,
	CASE WHEN porcentaje_inversion < 0 THEN 0.0 ELSE porcentaje_inversion END AS porcentaje_inversion
FROM tabla_kmeans
WHERE
  total_patrimonio >= 0 OR saldo_cuenta >= 0;